### ISSUE TITLE
 ReferenceError: cb is not defined

### ISSUE THREAD

**Issue by srkkhan** [danieljin/yelpv3#1]
```
 this.get(resource, params, cb).then((data) => {
                                     ^

ReferenceError: cb is not defined
    at Request.request.get [as _callback] (/var/www/html/peerfoodbotlocal/node_modules/yelpv3/index.js:58:38)
    at Request.self.callback (/var/www/html/peerfoodbotlocal/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/html/peerfoodbotlocal/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/html/peerfoodbotlocal/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

my request was:
 yelp.search({categories:'restaurants',offset:0,limit:limit,latitude:latitude,longitude:longitude})
                              .then(function (data) {}

Here,latitude and longitude was of texas and limit was 10.
And when i enter latitude and longitude of location which is not served by yelp at that time it gives no error.but return 400 status code and gives no data but at least that doesn't give compile time error.

**Comment by danieljin** [comment]
Thanks, I'll look into this.

**Comment by danieljin** [comment]
I have since removed callback functionality as I don't see much use for it.
